apiVersion: v1

kind: Service

metadata:
  name: server
  labels:
    app: backend

spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-deployment
  labels:
    app: backend

spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: server
          image: docker.io/hishammaged10/k8s_server
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 2
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 2
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 10
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
  
---
apiVersion: v1

kind: Service

metadata:
  name: client
  labels:
    app: frontend

spec:
  type: NodePort

  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: client
          image: docker.io/hishammaged10/k8s_client
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /accessServer
              port: 80
            initialDelaySeconds: 15
            failureThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /accessServer
              port: 80
            failureThreshold: 10
            initialDelaySeconds:
          resources:
            limits:
              memory: 128Mi
              cpu: 100m


